<?php

namespace App\Providers\Filament;

use Filament\Http\Middleware\Authenticate;
use Filament\Http\Middleware\DisableBladeIconComponents;
use Filament\Http\Middleware\DispatchServingFilamentEvent;
use Filament\Pages;
use Filament\Panel;
use Filament\PanelProvider;
use Filament\Support\Colors\Color;
use Filament\Widgets;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\View\Middleware\ShareErrorsFromSession;
use Filament\Navigation\NavigationGroup; // For defining navigation groups
use Filament\Support\Enums\MaxWidth;

// Note: You don't need to import individual Resource classes here anymore
// if you are using discoverResources() and not building navigationItems manually.

class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->login() // Uses Laravel's default login or Filament's if configured
            ->colors([
                'primary' => Color::Amber, // Example primary color
                // You can also define 'danger', 'gray', 'info', 'success', 'warning'
            ])
             ->maxContentWidth(MaxWidth::Screen->value)
            ->discoverResources(in: app_path('Filament/Resources'), for: 'App\\Filament\\Resources')
            ->discoverPages(in: app_path('Filament/Pages'), for: 'App\\Filament\\Pages')
            ->pages([
                Pages\Dashboard::class, // Default Filament dashboard page
            ])
            ->discoverWidgets(in: app_path('Filament/Widgets'), for: 'App\\Filament\\Widgets')
            ->widgets([
                // Widgets\AccountWidget::class, // Default user account widget in the top right
                // Widgets\FilamentInfoWidget::class, // Shows Filament version, etc.
            ])
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
            ])
            ->authMiddleware([
                Authenticate::class, // Filament's authentication middleware
            ])
            ->sidebarCollapsibleOnDesktop() // Makes the sidebar collapsible on desktop
            ->spa() // Optional: Enable Single Page Application mode for faster navigation within admin panel
            ->navigationGroups([ // Define the groups for your sidebar
                NavigationGroup::make('Business Management') // Key for this group
                    ->label('Business & Listings')          // Display label
                    ->icon('heroicon-o-building-storefront') // Updated icon to match BusinessResource
                    ->collapsed(false), // Start expanded
                NavigationGroup::make('Content Attributes')    // Key
                    ->label('Attributes & Taxonomies')   // Display label
                    ->icon('heroicon-o-tag')
                    ->collapsed(false),
                NavigationGroup::make('Site Administration')   // Key
                    ->label('Users & Site Config')     // Display label
                    ->icon('heroicon-o-users')         // Updated icon to match UserResource
                    ->collapsible(true), // Can be collapsed by default if many items
				NavigationGroup::make('Moderation')
					->label('Content Moderation')
					->icon('heroicon-o-shield-check'),
            ]);
            // THE ->navigation(...) CLOSURE HAS BEEN REMOVED.
            // Navigation items will be automatically generated by discoverResources()
            // and placed into the groups above based on the $navigationGroup
            // static property in each Resource class.
            // Visibility will be controlled by the canViewAny() static method in each Resource.
    }
}